### ISSUE TITLE
Feature request: ability to CRUD without needing to bind as a feathers service

### ISSUE THREAD

**Issue by dbkaplun** [feathersjs/feathers-knex#19]
Theoretically I am passing all the info needed in order for feathers-knex to CRUD with the database. There's no reason why I should have to bind to a URL in order to `.create`, for example.

P.S. sorry if I'm filing too many issues, feel free to close!

**Comment by daffl** [comment]
No problem at all, thank you for asking questions!

This seems similar to https://github.com/feathersjs/feathers-hooks/issues/25 right? You can use the Knex adapter standalone (have a look at the tests at https://github.com/feathersjs/feathers-knex/blob/33dfb50806e5f17186e60e8c4d751d7f29c526d4/test/index.test.js) but as already mentioned in the other issue you won't get any of the hook or real-time functionality or flexible method parameters (e.g. instead of just calling `service.create(data)` you always have to use `service.create(data, {}, function() {})`).

Generally, registering a service with your app shouldn't be a big problem considering what you get from it. We probably do need an easier way than special hooks to disable public access though.

**Comment by ekryski** [comment]
Ya I think we should create a proper issue around that. I had one open for [disabling service methods](https://github.com/feathersjs/feathers/issues/106) but you also might want all the service methods available, just not public.

**Comment by daffl** [comment]
This can now be done with the [disable hook](http://docs.feathersjs.com/hooks/bundled.html#disable).
